### ISSUE TITLE
Comparator is really `(nextDeps, prevDeps)`

### ISSUE THREAD

**Issue by mikew** [kotarella1110/use-custom-compare#186]
The docs state that the arguments passed to the comparator function are `(prevDeps, nextDeps)`, but the code in ... https://github.com/kotarella1110/use-custom-compare/blob/0d3fb19373cf9c9845eba28cc9514792003fc8e2/src/useCustomCompareMemoize.ts#L38 ... is more like `(nextDeps, prevDeps)`

**Comment by kotarella1110** [comment]
@mikew Oops! I will fix this. Thanks.
