### ISSUE TITLE
[QUESTION]: Error: useCustomCompareMemo should not be used with dependencies that are all primitive values. Use React.useMemo instead.

### ISSUE THREAD

**Issue by simplecommerce** [kotarella1110/use-custom-compare#377]
Hi,

Quick question, I am testing your library to see changes in array of objects or objects, and have noticed that it throws an error when the array or object is set to null and keeps saying to use `useMemo` instead.

Is this normal behavior?

**Comment by kotarella1110** [comment]
@simplecommerce Hi, If deps are all premitive, throw the error.

https://github.com/kotarella1110/use-custom-compare/blob/7d86f25fa73e478401f03d9632454a74844d5350/src/useCustomCompareMemoize.ts#L4-L6

Considering the various use cases, it may be better not to throw an error if it is null.
Do you think I should fix this?

**Comment by simplecommerce** [comment]
@kotarella1110 maybe simply write a warning/notice in your documentation that this should only be used with non-primitive values and leave the responsibility to the programmer? Thanks for your response!

**Comment by kotarella1110** [comment]
@simplecommerce please review #380 PR 🙏🏻
