### ISSUE TITLE
Typescript error - cannot pass type DependencyList

### ISSUE THREAD

**Issue by stopdropandrew** [kotarella1110/use-custom-compare#458]
Hi! We wrap this lib for a useDeepEqualCompare hook and it stopped working when we grabbed the latest version when we try to pass a `DependencyList` into `useCustomCompareMemo`. The error is:

```
Argument of type 'DependencyList' is not assignable to parameter of type 'any[]'.
  The type 'DependencyList' is 'readonly' and cannot be assigned to the mutable type 'any[]'.ts(2345)
```

Here's an example [codesandbox](https://codesandbox.io/s/kind-moon-lhtk7?file=/src/App.tsx)

I think at this [line](https://github.com/kotarella1110/use-custom-compare/pull/378/files#diff-e7b889203e22881a3fbf55edab71b14894ff21192a887c79f20ced8a86ae5f95R10) the _type_ of `deps` should be `TDependencyList` and not `[...TDependencyList]` (which ends up as `any[]`)

Thanks!

**Comment by kotarella1110** [comment]
@stopdropandrew Thank you for your feedback!
I will fix it soon 👍

**Comment by stopdropandrew** [comment]
Thanks a lot!
