### ISSUE TITLE
Feature request: ESLint Rules of Hooks plugin integration

### ISSUE THREAD

**Issue by mosesoak** [kotarella1110/use-custom-compare#529]
Hi, thanks for this useful utility. Wanted to mention that our team relies heavily on the ESLint Rules of Hooks plugin: https://www.npmjs.com/package/eslint-plugin-react-hooks. It is excellent in helping keep deps arrays  up to date and correct.

Unfortunately using this utility knocks out that functionality. How hard would it be to write some kind of integration?

Thanks for considering it!

**Comment by mosesoak** [comment]
Oh sweet, I just realized I can restore functionality by doing,
```js
import { useCustomCompareMemo as useMemo } from 'use-custom-compare';
```
However, I wouldn't be able to import the original react hook in the same file. Still this is a decent workaround.

**Comment by kotarella1110** [comment]
@mosesoak I think this can be solved by using `additionalHooks` option 👍🏻 

https://www.npmjs.com/package/eslint-plugin-react-hooks#advanced-configuration

```js
{
  "rules": {
    // ...
    "react-hooks/exhaustive-deps": ["warn", {
      "additionalHooks": "useCustomCompareMemo"
    }]
  }
}
```

**Comment by mosesoak** [comment]
Thanks @kotarella1110! You might want to add that to your main README as it is super useful to know.

**Comment by kotarella1110** [comment]
@mosesoak Thanks! I will!
If you want to create a PR, I will gladly wait for it 🙌🏻
