### ISSUE TITLE
React 18 peer dependency

### ISSUE THREAD

**Issue by philipaarseth** [kotarella1110/use-custom-compare#672]
Peer dependency has not been updated for react 18

**Comment by kotarella1110** [comment]
@philipaarseth I will fix 🙏

**Comment by sjbuysse** [comment]
Is it coming along? :)

**Comment by silberistgold** [comment]
Any updates on this? Should be pretty straightforward...

**Comment by kotarella1110** [comment]
@philipaarseth @sjbuysse @silberistgold 
Sorry for the delay in fixing this.
React 18 is now supported.
