### ISSUE TITLE
My thoughts about what should get passed to depsAreEqual

### ISSUE THREAD

**Issue by leqwasd** [kotarella1110/use-custom-compare#713]
Hello,

I was sitting and wondering about this - how the equality of the dependencies should be checked. Specifically about the first argument of the `depsAreEqual` function, and maybe, how it could be optimised.
Maybe we can discuss it here.

So let's say we have a component like this:

```tsx
const isReallyEqual = (a: readonly [number[]], b: readonly [number[]]): boolean => {
    if (a[0] === b[0]) {
         return true;
    }
    return _.isEqual(a[0], b[0]);
};
const MyComponent: React.FC = () => {
    // Note, initial state [1,2]
    const [state, setState] = React.useState([1, 2]);
    const [, setVoidState] = React.useState<{}>({});
    const clickToRerender = React.useCallback(() => {
        setVoidState({});
    }, []);
    const clickToSetTheSameState = React.useCallback(() => {
        setState([1, 2]);
    }, []);
    const moized = useCustomCompareMemo(
        () => {
            console.log("moized_deep");
            return state;
        },
        [state],
        isReallyEqual
    );
    return (
        <div>
            <div>
                <button onClick={clickToSetTheSameState}>clickToSetTheSameState</button>
                <button onClick={clickToRerender}>ClickToRerender</button>
            </div>
            <pre>{moized}</pre>
        </div>
    );
};
```
Trivial component, and trivial data. But imagine, the data get's bigger and more complex.
But I care more about the "collection" of data and whether it changes or not rather than individual elements of the data.

So the scenarios here - 

1. Component renders
    1. `isReallyEqual` get's  called and returns false since it is the first render
    1. `moized` gets calculated 
2. User clicks on `ClickToRerender`
    1. `isReallyEqual` get's  called and returns true since previous dependencies are strictly equal current dependencies
    1. `moized` does not get calculated 
3. User clicks on `ClickToRerender` And so on 
    1. `isReallyEqual` get's  called and returns true since previous dependencies are strictly equal current dependencies
    1. `moized` does not get calculated 
4. Then user click `clickToSetTheSameState`
    1. `isReallyEqual` get's  called and returns true but because they are equal by value, not by reference. (this takes more to compare, than simple ===)
    1. `moized`  does not get calculated 
5. User clicks on `ClickToRerender`
    1. `isReallyEqual`  get's  called and returns true but because they are equal by value, not by reference. (this takes more to compare, than simple ===)
    1. `moized` does not get calculated 
6. User clicks on `ClickToRerender`
    1, Long story short - from now on, it goes and compares the original argument that was equal to the current argument by value.
    
 
My point: Shouldn't it compare the previous dependencies that were equal to the current dependencies?
If `dependencies A === dependencies B` and `dependencies B === dependencies C`
then `dependencies A === dependencies C` - but they shouldn't always be compared deeply, in my opinion.

I wrote something, but I am not sure if this will handle all of the situations:

```ts
export function useCustomCompareMemoize<TDependencyList extends DependencyList>(
    deps: readonly [...TDependencyList],
    depsAreEqual: DepsAreEqual<readonly [...TDependencyList]>
): readonly [...TDependencyList] {
    const ref = useRef<readonly [...TDependencyList]>(deps);
    const refPrevious = useRef<readonly [...TDependencyList]>(deps);

    const areEqual = depsAreEqual(refPrevious.current, deps);
    if (!areEqual) {
        ref.current = deps;
    } else {
        refPrevious.current = deps;
    }

    return ref.current;
}

```

**Comment by kotarella1110** [comment]
@leqwasd 
Thanks for your feedback!
I will fix this.

codesandbox: https://codesandbox.io/p/sandbox/affectionate-paper-g8rozc
